dailyfresh/urls.py
#coding=utf-8
"""dailyfresh URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
#分发路由信息
urlpatterns = [
    #url后台
    url(r'^admin/', include(admin.site.urls)),
    #url用户中心
    url(r'^user/',include('df_user.urls')),
    #url富文本编辑器
    url(r'^tinymce/',include('tinymce.urls')),
    #url商品
    url(r'^goods/',include('df_goods.urls')),
    #url购物车
    url(r'^cart/',include('df_cart.urls')),
    #url订单
    url(r'^order/',include('df_order.urls')),
]

df_cart/urls.py
# coding=utf-8

from django.conf.urls import url
import views

# 购物车路由分发
urlpatterns=[
    # 购物车展示
    url(r'^$',views.cart),
    # 购物车商品增加
    url(r'^add(\d+)_(\d+)/$',views.add),
    # 购物车信息修改  异步
    url(r'^edit(\d+)_(\d+)/$',views.edit),
    # 购物车信息删除
    url(r'^delete(\d+)/$',views.delete),
]

df_user/urls.py
#coding=utf-8

from django.conf.urls import url
import views
#用户应用内的路由分发
urlpatterns=[
    #用户注册
    url(r'^register/$',views.register),
    #用户注册处理
    url(r'^register_handle/$',views.register_handle),
    #用户登陆
    url(r'^login/$',views.login),
    #用户登陆出来
    url(r'^login_handle/$',views.login_handle),
    #用户中心显示
    url(r'^info/$',views.info),
    #用户信息补全
    url(r'^site/$',views.site),
    #用户退出登陆
    url(r'^logout/$',views.logout),
    #用户查看自己的订单
    url(r'^order(\d*)/$',views.order),
    # 修改密码页面展示
    url(r'^passwd/',views.passwd),
    # 修改密码处理逻辑
    url(r'passwd_handle',views.passwd_handle),
]

df_order/models.py
#coding=utf-8

from django.db import models

# 订单表模型
class OrderInfo(models.Model):
    oid = models.CharField(max_length=20, primary_key=True)
    user = models.ForeignKey('df_user.UserInfo')
    odate = models.DateTimeField(u'购买日期',auto_now=True)
    # 付款属性
    oIsPay = models.BooleanField(u'是否付款',default=False)
    # 总价
    ototal = models.DecimalField(u'总价',max_digits=6, decimal_places=2)
    oaddress = models.CharField(u'收货地址',max_length=150)

    def __str__(self):
        if self.oIsPay==True:
            return self.oaddress
        else :
            return '未付款'

    # 修改后台显示名字
    class Meta:
        verbose_name_plural='订单管理'

# 订单详表
class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('df_goods.GoodsInfo')
    order = models.ForeignKey(OrderInfo)
    # 总价
    price = models.DecimalField(u'价钱',max_digits=5, decimal_places=2)
    # 数量
    count = models.IntegerField(u'数量')
    # 统计销量是否统计进去
    isTrue=models.BooleanField(default=False)

    # 修改后台显示名字
    class Meta:
        verbose_name_plural = '发货管理'
#销量统计
class sales(models.Model):
    # 水果名称
    goods = models.ForeignKey('df_goods.GoodsInfo')
    # 销量
    count=models.IntegerField(u'销量')
    # 销售额
    totalprice=models.DecimalField(u'销售额',max_digits=5, decimal_places=2)
 # 修改后台显示名字
    class Meta:
        verbose_name_plural = '销量查看'
    def __str__(self):
        return self.goods.gtitle

df_user/models.py
# coding=utf-8

from django.db import models


# 构建用户模型
class UserInfo(models.Model):
    # u'***'修改的是后台展示信息的名字字段
    uname = models.CharField(u'用户名', max_length=20)
    # 密码采用暗文，sha1加密转换为40字节
    upwd = models.CharField(u'密码', max_length=40)
    uemail = models.CharField(u'电子邮箱', max_length=30)
    ushow = models.CharField(u'收件人名字', max_length=20, default='')
    uaddress = models.CharField(u'收件地址', max_length=100, default='')
    uyoubian = models.CharField(u'收件邮编', max_length=6, default='')
    uphone = models.CharField(u'收件人电话', max_length=11, default='')

    # default,blank是python层面的约束,不影响数据库表结构

    # 用户对象名字返回，后台订单管理现实
    def __str__(self):
        return self.uname.encode('utf-8')

    # 修改后台管理界面显示
    class Meta:
        verbose_name_plural = '用户管理'

df_user/views.py
# coding=utf-8

from django.shortcuts import render, redirect
from models import *
from hashlib import sha1
from django.http import JsonResponse, HttpResponseRedirect,HttpResponse
from . import user_decorator
from df_goods.models import *
from django.core.paginator import Paginator, Page
from df_order.models import *


# 展示注册界面
def register(request):
    return render(request, 'df_user/register.html')


# 用户注册处理逻辑
def register_handle(request):
    # 接受用户输入，POST方式
    post = request.POST
    uname = post.get('user_name')
    upwd = post.get('pwd')
    upwd2 = post.get('cpwd')
    uemail = post.get('email')
    # 判断两次密码是否一致,
    if upwd != upwd2:
        return redirect('/user/register/')
    # 密码加密，采用sha1加密
    s1 = sha1()
    s1.update(upwd)
    upwd3 = s1.hexdigest()
    # 创建对象
    user = UserInfo()
    user.uname = uname
    user.upwd = upwd3
    user.uemail = uemail
    # 将用户信息保存进数据库
    user.save()
    # 注册成功,转到登陆页面
    return redirect('/user/login/')

#修该密码页面展示
def passwd(request):
    return render(request,'df_user/passwd.html')

#修改密码处理逻辑
def passwd_handle(request):
    # 接受用户输入，POST方式
    post = request.POST
    uname=post.get('user_name')
    uemail=post.get('email')
    pwd1=post.get('pwd1')
    pwd2=post.get('pwd2')
    # 根据用户名查询对象
    users = UserInfo.objects.filter(uname=uname)  # []
    if len(users)==1:
        #判断邮箱信息
        if users[0].uemail==uemail:
            if pwd1==pwd2:
                # 密码加密，采用sha1加密
                s1 = sha1()
                s1.update(pwd1)
                pwd3 = s1.hexdigest()
                user=users[0]
                user.upwd=pwd3
                user.save()
                # 修改密码成功,转到登陆页面
                return redirect('/user/login/')
            else:
                return HttpResponse('两次输入密码不一样')
        else:
            return HttpResponse('邮箱输入错误！')
    else:
        return HttpResponse('查无此人，请返回后重新输入！')


# 异步处理用户名重复
def register_exist(request):
    # 采用get请求
    uname = request.GET.get('uname')
    # 查询数据库中采用这个用户名的数量，如果为0，那就是未被使用，可以使用
    count = UserInfo.objects.filter(uname=uname).count()
    # 展示模板
    return JsonResponse({'count': count})


# 登陆处理
def login(request):
    uname = request.COOKIES.get('uname', '')
    context = {'title': '用户登陆', 'error_name': 0, 'error_pwd': 0, 'uname': uname}
    return render(request, 'df_user/login.html', context)

# 登陆处理
def login_handle(request):
    # 接收请求信息
    post = request.POST
    uname = post.get('username')
    upwd = post.get('pwd')
    jizhu = post.get('jizhu', 0)
    # 根据用户名查询对象
    users = UserInfo.objects.filter(uname=uname)  # []
    # 判断：如果未查询到则用户名错，如果查到则判断密码是否正确，正确则转到
    if len(users) == 1:
        # 将传来的密码sha1加密后与数据库加密过的密码对比
        s1 = sha1()
        s1.update(upwd)
        # 判断密码是否正确
        if s1.hexdigest() == users[0].upwd:

            url = request.COOKIES.get('url', '/goods/')
            red = HttpResponseRedirect(url)
            # 记住用户名
            if jizhu != 0:
                red.set_cookie('uname', uname)
            else:
                red.set_cookie('uname', '', max_age=-1)
            request.session['user_id'] = users[0].id
            request.session['user_name'] = uname
            return red
        # 密码错误转到用户登陆页
        else:
            context = {'title': '用户登录', 'error_name': 0, 'error_pwd': 1, 'uname': uname, 'upwd': upwd}
            return render(request, 'df_user/login.html', context)
    # 没有这个用户名，转到登陆页
    else:
        context = {'title': '用户登录', 'error_name': 1, 'error_pwd': 0, 'uname': uname, 'upwd': upwd}
        return render(request, 'df_user/login.html', context)

# 退出登陆
def logout(request):
    # 清除session信息
    request.session.flush()
    # 转向到首页
    return redirect('/goods/')

#装饰器检测是否帐号已经登陆
@user_decorator.login
def info(request):
    # 最近浏览
    goods_ids = request.COOKIES.get('goods_ids', '')
    goods_ids1 = goods_ids.split(',')
    goods_list = []
    # 如果没浏览则返回空的的浏览列表
    if goods_ids1==['']:
        goods_list==[]
    # 如果浏览了则返浏览的信息
    else:
        for goods_id in goods_ids1:
            goods_list.append(GoodsInfo.objects.get(id=int(goods_id)))
    # 根据登陆的信息，查询登陆用户的各项信息
    user = UserInfo.objects.get(id=request.session['user_id'])
    user_eamil = user.uemail
    user_address = user.uaddress
    user_phone = user.uphone
    # 构造上下文
    context = {'title': '用户中心',
               'user_eamil': user_eamil,
               'user_name': request.session['user_name'],
               'user_address': user_address,
               'user_phone': user_phone,
               # 最近浏览信息
               'goods_list': goods_list,
               }
    # 渲染模板
    return render(request, 'df_user/user_center_info.html', context)

# 装饰器检测帐号是否登陆
@user_decorator.login
def order(request, pindex):
    # 查询这个账户的订单信息，倒序排列
    order_list = OrderInfo.objects.filter(user_id=request.session['user_id']).order_by('-oid')
    # 分页展示，每页最多展示2个订单
    paginator = Paginator(order_list, 2)
    # 传来url中的页面信息如果为空，就展示第一页
    if pindex == '':
        pindex = '1'
    page = paginator.page(int(pindex))
    # 构造上下文传递
    context = {'title': '天天生鲜用户中心',
               # 分页信息
               'paginator': paginator,
               'page': page, }
    # 渲染模板
    return render(request, 'df_user/user_center_order.html', context)

# 装饰检测帐号是否登陆
@user_decorator.login
def site(request):
    # 根据session的信息查询用户的相应信息
    user = UserInfo.objects.get(id=request.session['user_id'])
    # 如果为POST请求，则是修改信息，构造对象存储，保存
    if request.method == 'POST':
        post = request.POST
        user.ushow = post.get('ushow')
        user.uaddress = post.get('uaddress')
        user.uyoubian = post.get('uyoubian')
        user.uphone = post.get('uphone')
        user.save()
    context = {'title': '用户中心', 'user': user}
    # 渲染模板
    return render(request, 'df_user/user_center_site.html', context)

templates/df_user/login.html
{%extends 'base_foot.html'%}
{%block head%}
<script>
	$(function (){
		name_error=false;
		pwd_error=false;

		if({{error_name}}==1){
			$('.user_error').html('用户名错误').show();
		}

		if({{error_pwd}}==1){
			$('.pwd_error').html('密码错误').show();
		}

		$('.name_input').blur(function (){
			if($('.name_input').val().length==0){
				$('.user_error').html('请填写用户名').show();
				name_error=false;
			}else{
				$('.user_error').hide();
				name_error=true;
			}
		});

		$('.pass_input').blur(function(){
			if($(this).val().length==0){
				$('.pwd_error').html('请输入密码').show();
				pwd_error=false;
			}else{
				$('.pwd_error').hide();
				pwd_error=true;
			}
		});


	})

</script>
{%endblock head%}
{% block body %}
<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/images/logo2.png"></a>
</div>
	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register">立即注册</a>
				</div>
				<div class="form_input">
					<form action="/user/login_handle/" method="post">
						{% csrf_token%}
						<input type="text" name="username" class="name_input" value="{{uname}}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" value="{{upwd}}" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="/user/passwd/">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

{%endblock body%}

templates/df_user/passwd.html
{%extends 'base_foot.html'%}

{% block head %}

{%endblock head %}

{% block body %}

<body>
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo2.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>修改密码</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="/user/passwd_handle" method="post">
					{% csrf_token%}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>				
					<li>
						<label>新密码:</label>
						<input type="password" name="pwd1" id="pwd1">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>新密码:</label>
						<input type="password" name="pwd2" id="cpwd2">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天水果用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="修改密码" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>

{%endblock body%}

templates/df_user/register.html
{%extends 'base_foot.html'%}

{% block head %}
	<script type="text/javascript" src="/static/js/register.js"></script>
{%endblock head %}

{% block body %}


	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo2.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="/user/register_handle/" method="post">
					{% csrf_token%}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<spanclass="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" >
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{%endblock body%}

templates/df_user/user_center_info.html
{%extends 'base_foot.html'%}
{% block head %}
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天水果!</div>
			<div class="fr">
				{%if request.session.user_name|default:'' != ''%}
				<div class="login_btn fl">
					欢迎您：<em>{{request.session.user_name}}</em>
					<span>|</span>
					<a href="/user/logout/">退出</a>
				</div>
				{%else%}
				<div class="login_btn fl">
					<a href="/user/login/">登录</a>
					<span>|</span>
					<a href="/user/register/">注册</a>
				</div>
				{%endif%}
				<div class="user_link fl">
					<span>|</span>
					<a href="/user/info/">用户中心</a>
					<span>|</span>
					<a href="/cart/">我的购物车</a>
					<span>|</span>
					<a href="/user/order/">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="/goods/" class="logo fl"><img src="/static/images/logo1.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<!--<input type="text" class="input_text fl" name="" placeholder="搜索商品">-->
			<!--<input type="button" class="input_btn fr" name="" value="搜索">-->
			<form method='get' action='/goods/search/' target='_blank'>
				<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
				<input type="submit" class="input_btn fr"  value="搜索">
			</form>
		</div>
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/" class="active">· 个人信息</a></li>
				<li><a href="/user/order/">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{user_name}}</li>
							<li><span>联系方式：</span>{{user_phone}}</li>
							<li><span>联系地址：</span>{{user_address}}</li>
						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>

				<div class="has_view_list">
					<ul class="goods_type_list clearfix">

						{%if goods_list%}

						{%for good in goods_list%}
						<li>
					<a href="/goods/{{good.id}}"><img src="/static/{{good.gpic}}"></a>
					<h4><a href="/goods/{{good.id}}">{{good.gtitle}}</a></h4>
					<div class="operate">
						<span class="prize">￥{{good.gprice}}</span>
						<span class="unit">{{good.gprice}}/{{good.gunit}}</span>
						<a href="/cart/add{{good.id}}_1/" class="add_goods" title="加入购物车"></a>
					</div>
						</li>
						{%endfor%}
						{%endif%}
					</ul>
				</div>
		</div>
	</div>
{%endblock head %}
{% block body %} {%endblock body%}

templates/df_user/user_center_order.html
{%extends 'base_foot.html'%}
{% block head %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天水果!</div>
			<div class="fr">
				{%if request.session.user_name|default:'' != ''%}
				<div class="login_btn fl">
					欢迎您：<em>{{request.session.user_name}}</em>
					<span>|</span>
					<a href="/user/logout/">退出</a>
				</div>
				{%else%}
				<div class="login_btn fl">
					<a href="/user/login/">登录</a>
					<span>|</span>
					<a href="/user/register/">注册</a>
				</div>
				{%endif%}
				<div class="user_link fl">
					<span>|</span>
					<a href="/user/info/">用户中心</a>
					<span>|</span>
					<a href="/cart/">我的购物车</a>
					<span>|</span>
					<a href="/user/order/">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="/goods/" class="logo fl"><img src="/static/images/logo1.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<!--<input type="text" class="input_text fl" name="" placeholder="搜索商品">-->
			<!--<input type="button" class="input_btn fr" name="" value="搜索">-->
			<form method='get' action='/goods/search/' target='_blank'>
				<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
				<input type="submit" class="input_btn fr"  value="搜索">
			</form>
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order/" class="active">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
    {%if paginator.count > 0%}
		  {%for order in page%}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{order.odate}}</li>
					<li class="col02">订单号：{{order.oid}}</li>
					<li class="col02 stress">{%if order.oIsPay%}已支付{%else%}未支付{%endif%}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
							   {%for detail in order.orderdetailinfo_set.all%}
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="/static/{{detail.goods.gpic}}"></li>
									<li class="col02">{{detail.goods.gtitle|slice:'10'}}<em><span>{{detail.price}}</span>元/{{detail.goods.gunit}}</em></li>
									<li class="col03">{{detail.count}}</li>
									<li class="col04"> </li>
								</ul>
								{%endfor%}
								</td>
							<td width="15%">{{order.ototal}}元</td>
							{%if order.oIsPay%}
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
							{%else%}
						<td width="15%">待付款</td>
						<td width="15%"><a href="/order/pay{{order.oid}}/" class="oper_btn">去付款</a></td>
						{%endif%}
						</tr>
					</tbody>
				</table>
      {%endfor%}

				<div class="pagenation">
				{%if page.has_previous%}
					<a href="/user/order{{page.previous_page_number}}"><上一页</a>
					{%endif%}

					{%for pindex in paginator.page_range%}
					{%if pindex == page.number%}
					<a href="#" class=active>{{pindex}}</a>
					{%else%}
					<a href="/user/order{{pindex}}/">{{pindex}}</a>
					{%endif%}
					{%endfor%}

					{%if page.has_next%}
					<a href="/user/order{{page.next_page_number}}/">下一页></a>
					{%endif%}
					</div>
					{%else%}
				暂无订单信息
				{%endif%}
		</div>
	</div>


{%endblock head %}
{% block body %} {%endblock body%}

templates/df_user/user_center_site.html
{%extends 'base_foot.html'%}
{% block head %}
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天水果!</div>
			<div class="fr">
				{%if request.session.user_name|default:'' != ''%}
				<div class="login_btn fl">
					欢迎您：<em>{{request.session.user_name}}</em>
					<span>|</span>
					<a href="/user/logout/">退出</a>
				</div>
				{%else%}
				<div class="login_btn fl">
					<a href="/user/login/">登录</a>
					<span>|</span>
					<a href="/user/register/">注册</a>
				</div>
				{%endif%}
				<div class="user_link fl">
					<span>|</span>
					<a href="/user/info/">用户中心</a>
					<span>|</span>
					<a href="/cart/">我的购物车</a>
					<span>|</span>
					<a href="/user/order/">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="/goods/" class="logo fl"><img src="/static/images/logo1.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<!--<input type="text" class="input_text fl" name="" placeholder="搜索商品">-->
			<!--<input type="button" class="input_btn fr" name="" value="搜索">-->
			<form method='get' action='/goods/search/' target='_blank'>
				<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
				<input type="submit" class="input_btn fr"  value="搜索">
			</form>
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/site/">· 全部订单</a></li>
				<li><a href="/user/order/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：{{ user.uaddress }}</dt>
						<dd> （{{ user.ushow }} 收） {{ user.uphone }}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/site/" method="post">
						{% csrf_token%}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ushow" value="{{ user.ushow }}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="uaddress" >{{ user.uaddress }}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="uyoubian" value="{{ user.uyoubian }}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="uphone" value="{{ user.uphone }}">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>

{%endblock head %}
{% block body %} {%endblock body%}